-- Multi-tenant SaaS plan catalog + tenant plan assignment
-- Idempotent migration: safe to run multiple times.

CREATE TABLE IF NOT EXISTS public.plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  price_monthly NUMERIC(12,2) NOT NULL DEFAULT 0,
  max_cadastros INTEGER NOT NULL CHECK (max_cadastros >= 0),
  features JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT plans_name_check CHECK (name IN ('standard', 'simple', 'explorer', 'enterprise')),
  CONSTRAINT plans_features_is_object CHECK (jsonb_typeof(features) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_plans_name ON public.plans(name);

-- Add plan_id without changing existing tenant status/circuit-breaker semantics.
ALTER TABLE public.tenants
  ADD COLUMN IF NOT EXISTS plan_id BIGINT;

-- Ensure FK exists (idempotent with catalog check).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'tenants_plan_id_fkey'
      AND conrelid = 'public.tenants'::regclass
  ) THEN
    ALTER TABLE public.tenants
      ADD CONSTRAINT tenants_plan_id_fkey
      FOREIGN KEY (plan_id)
      REFERENCES public.plans(id)
      ON UPDATE RESTRICT
      ON DELETE RESTRICT;
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_tenants_plan_id ON public.tenants(plan_id);

-- Keep backward compatibility for existing rows by assigning default plan if NULL.
INSERT INTO public.plans (name, price_monthly, max_cadastros, features)
VALUES
  (
    'simple',
    99.00,
    1000,
    '{
      "secretariado": false,
      "lembrete_monitoramento": true,
      "gerente_exclusivo": false
    }'::jsonb
  ),
  (
    'standard',
    199.00,
    5000,
    '{
      "secretariado": true,
      "lembrete_monitoramento": true,
      "gerente_exclusivo": false
    }'::jsonb
  ),
  (
    'explorer',
    399.00,
    15000,
    '{
      "secretariado": true,
      "lembrete_monitoramento": true,
      "gerente_exclusivo": true
    }'::jsonb
  ),
  (
    'enterprise',
    999.00,
    100000,
    '{
      "secretariado": true,
      "lembrete_monitoramento": true,
      "gerente_exclusivo": true
    }'::jsonb
  )
ON CONFLICT (name) DO UPDATE
SET
  price_monthly = EXCLUDED.price_monthly,
  max_cadastros = EXCLUDED.max_cadastros,
  features = EXCLUDED.features;

UPDATE public.tenants t
SET plan_id = p.id
FROM public.plans p
WHERE t.plan_id IS NULL
  AND p.name = 'simple';

-- For future inserts, default to "simple" without hardcoding app-side inserts.
DO $$
DECLARE
  v_simple_plan_id BIGINT;
BEGIN
  SELECT id INTO v_simple_plan_id
  FROM public.plans
  WHERE name = 'simple'
  LIMIT 1;

  IF v_simple_plan_id IS NOT NULL THEN
    EXECUTE format(
      'ALTER TABLE public.tenants ALTER COLUMN plan_id SET DEFAULT %s',
      v_simple_plan_id
    );
  END IF;
END
$$;

-- Enforce assignment after backfill.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'tenants'
      AND column_name = 'plan_id'
      AND is_nullable = 'YES'
  ) THEN
    ALTER TABLE public.tenants
      ALTER COLUMN plan_id SET NOT NULL;
  END IF;
END
$$;

-- RLS compatibility: keep tenant-isolation behavior and expose read-only plan catalog.
ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can view plans" ON public.plans;
CREATE POLICY "Authenticated users can view plans"
ON public.plans
FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS "Service role manages plans" ON public.plans;
CREATE POLICY "Service role manages plans"
ON public.plans
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);
