-- Pricing catalog upgrade + subscriptions table

ALTER TABLE public.plans
  ADD COLUMN IF NOT EXISTS slug TEXT,
  ADD COLUMN IF NOT EXISTS price_annual NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS activation_fee NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS is_enterprise BOOLEAN NOT NULL DEFAULT false;

UPDATE public.plans
SET slug = LOWER(name)
WHERE slug IS NULL;

ALTER TABLE public.plans
  ALTER COLUMN slug SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'plans_slug_key'
      AND conrelid = 'public.plans'::regclass
  ) THEN
    ALTER TABLE public.plans
      ADD CONSTRAINT plans_slug_key UNIQUE (slug);
  END IF;
END
$$;

DROP TABLE IF EXISTS public.subscriptions CASCADE;

CREATE TABLE public.subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  plan_id BIGINT NOT NULL REFERENCES public.plans(id) ON DELETE RESTRICT,
  billing_cycle TEXT NOT NULL CHECK (billing_cycle IN ('monthly', 'annual')),
  processes_count INTEGER,
  status TEXT NOT NULL DEFAULT 'active',
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  renews_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_subscriptions_user_id ON public.subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_plan_id ON public.subscriptions(plan_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON public.subscriptions(status);

ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own subscriptions" ON public.subscriptions;
CREATE POLICY "Users can view own subscriptions"
ON public.subscriptions
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Service role manages subscriptions" ON public.subscriptions;
CREATE POLICY "Service role manages subscriptions"
ON public.subscriptions
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

INSERT INTO public.plans (name, slug, price_monthly, price_annual, activation_fee, max_cadastros, features, is_enterprise)
VALUES
(
  'STANDARD',
  'standard',
  300,
  240,
  0,
  150,
  jsonb_build_object(
    'monitoramento_diario', true,
    'ia_simplificada', true,
    'atendimento_humano', true,
    'suporte_whatsapp_email', true,
    'area_cliente', true,
    'conversas_ilimitadas', true,
    'secretariado_simples', false,
    'lembrete_monitoramento', false,
    'gerente_contas_exclusivo', false
  ),
  false
),
(
  'SIMPLE',
  'simple',
  570,
  456,
  0,
  300,
  jsonb_build_object(
    'monitoramento_diario', true,
    'ia_simplificada', true,
    'atendimento_humano', true,
    'suporte_whatsapp_email', true,
    'area_cliente', true,
    'conversas_ilimitadas', true,
    'secretariado_simples', true,
    'lembrete_monitoramento', false,
    'gerente_contas_exclusivo', false
  ),
  false
),
(
  'EXPLORER',
  'explorer',
  750,
  600,
  0,
  500,
  jsonb_build_object(
    'monitoramento_diario', true,
    'ia_simplificada', true,
    'atendimento_humano', true,
    'suporte_whatsapp_email', true,
    'area_cliente', true,
    'conversas_ilimitadas', true,
    'secretariado_simples', true,
    'lembrete_monitoramento', true,
    'gerente_contas_exclusivo', true
  ),
  false
),
(
  'ENTERPRISE',
  'enterprise',
  1300,
  1040,
  0,
  5000,
  jsonb_build_object(
    'monitoramento_diario', true,
    'ia_simplificada', true,
    'atendimento_humano', true,
    'suporte_whatsapp_email', true,
    'area_cliente', true,
    'conversas_ilimitadas', true,
    'secretariado_simples', true,
    'lembrete_monitoramento', true,
    'gerente_contas_exclusivo', true
  ),
  true
)
ON CONFLICT (slug) DO UPDATE
SET
  name = EXCLUDED.name,
  price_monthly = EXCLUDED.price_monthly,
  price_annual = EXCLUDED.price_annual,
  activation_fee = EXCLUDED.activation_fee,
  max_cadastros = EXCLUDED.max_cadastros,
  features = EXCLUDED.features,
  is_enterprise = EXCLUDED.is_enterprise;
